version: '3'

services:
 mariadb:
  container_name: mariadb
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  env_file: .env		
  volumes:
   - /home/theo/data/mariadb:/var/lib/mysql
  networks:
   - inception
  expose:
   - 3306
  restart: always
#  healthcheck:
#   test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
#   interval: 30s
#   retries: 5
#   start_period: 10s
#   timeout: 10s

 wordpress:
  container_name: wordpress
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - /home/theo/data/wordpress:/var/www/html
  depends_on:
   - mariadb
  networks:
   - inception
  expose:
   - 9000
  restart: on-failure

 nginx:
  container_name: nginx
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  env_file: .env
  volumes:
   - /home/theo/data/wordpress:/var/www/html
  depends_on:
   - wordpress
  networks:
   - inception
  ports:
   - 443:443
  restart: on-failure

volumes:
  wordpress:
   driver: local
  mariadb:
   driver: local

networks:
 inception:
  driver: bridge
