version: '3'

services:
 mariadb:
  container_name: mariadb
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  image: mariadb
  env_file: .env		
  volumes:
   - mariadb:/var/lib/mysql
  networks:
   - inception
  expose:
   - 3306
  restart: always
#  healthcheck:
#   test: ["CMD", "mysqladmin", "ping", "--host=localhost"]
#   interval: 30s
#   retries: 5
#   start_period: 10s
#   timeout: 10s

 wordpress:
  container_name: wordpress
  build:
   context: requirements/wordpress
   dockerfile: Dockerfile
  image: wordpress
  env_file: .env
  volumes:
   - wordpress:/var/www/html
  depends_on:
   - mariadb
  networks:
   - inception
  expose:
   - 9000
  restart: on-failure

 nginx:
  container_name: nginx
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  image: nginx
  env_file: .env
  volumes:
   - wordpress:/var/www/html
  depends_on:
   - wordpress
  networks:
   - inception
  ports:
   - 443:443
  restart: on-failure

volumes:
  wordpress:
   driver: local
   driver_opts:
    type: none
    device: "/home/flplace/data/wordpress"
    o: bind
  mariadb:
   driver: local
   driver_opts:
    type: none
    device: "/home/flplace/data/mariadb"
    o: bind

networks:
 inception:
  driver: bridge
